### ISSUE TITLE
usb error: operation timed out

### ISSUE THREAD

**Issue by itapai** [friedkeenan/GoldtreePy#1]
hi, wanted to give this tool a try, but i'm unable to install any game on the switch.

after loading the usb installation on goldleaf, i run goldtreepy.
i go through the 3 screens for the installation, but afterwards i keep getting this error ( no matter what the nsp is )

```
sudo python Goldtree.py ../games/donkey_kong.nsp 
Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Sending content '2d366c05465e6c77877c70712b8615b5.cnmt.nca'... (5 of 5)
Content was sent to Goldleaf.
Traceback (most recent call last):
  File "Goldtree.py", line 142, in <module>
    sys.exit(main())
  File "Goldtree.py", line 101, in main
    c=Command(raw=read(8))
  File "Goldtree.py", line 55, in read
    return ep[1].read(length).tobytes()
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

```

EDIT: after couple more of installs, i see the title in the home menu, but cannot launch the game ( corrupted ). 
usb installation stuck on 2/5

**Comment by friedkeenan** [comment]
Could you tell me what happens with Goldleaf? If it spits out a 0xd401 error, that's a known issue, and simply trying to install the game again fixed it for me when I got that error, but if that doesn't work try rebooting. Also could you tell me what NSP you're attempting to install, and how big it is?

**Comment by itapai** [comment]
I tried installing 2 games, one 4.2G, the other 14G ( there is more than enough free space on the sd card, double checked ).

I tried to reboot once, but it didnt help. 
One game got stuck on the instantly when i launched your script, the other one froze on step 2/5.
Like i said, the title was installed ( could see the icon on the menu ) but could not launch.
Goldleaf was stuck on that 2/5 screen, and the other time it threw an error and I had to reboot ( not sure what the error code was ).

**Comment by friedkeenan** [comment]
Do you by chance have a way of trying the original Goldtree with those NSPs to see if it's my script's fault? I know if you're using this you probably don't but a man can dream

**Comment by itapai** [comment]
I tried to get it to work with virtualbox, but couldn't access the switch via usb, sorry :P
I'll wait for the goldtree linux release. Guess ill use wifi for now

**Comment by wildwolfzj** [comment]
I have the same problem with newest py on mac.I think it because switch timeout and autoclose the screen.can the code auto-keep screen open.
