### ISSUE TITLE
Progress bar is very useful

### ISSUE THREAD

**Issue by carlosen14** [friedkeenan/GoldtreePy#13]
I would be great to have a progress bar or show progress percent

**Comment by carlosen14** [comment]
actually, i thought it was working and let it process it for 30 minutes but did not changed nor print something.. i guess wasn't working at all.. 

running on ubuntu 18.04.2
python 3.7

**Comment by friedkeenan** [comment]
Yeah, I'm gonna need more information. Which branch were you using, which version of Goldleaf, did you actually select the right thing in Goldleaf, etc.

**Comment by carlosen14** [comment]
No problem, I'll provide it when I get back to computer

**Comment by friedkeenan** [comment]
Gonna close this

**Comment by carlosen14** [comment]
sorry, i missed this.. just in case you still interested i tried with Goldleaf 0.5 and 0.6. N switch OFW 8.0.1, CFW 8.1.0-Reinx 2.4. I ended up using another method to do NSP installs. Thankyou!
