### ISSUE TITLE
Goldtree closes after clicking Remote PC (via USB)

### ISSUE THREAD

**Issue by gabn88** [friedkeenan/GoldtreePy#17]
I run goldtreePy and attach the switch via USB. Then when I click Remote PC (via USB) on the switch, Goldtree closes down and I get the error: Software closed due to an error (or something like that, I see the message in a different language).

In the console where GoldtreePy is running I see:

Received command: CommandId.GetDriveCount
Received command: CommandId.GetDriveInfo
Received command: CommandId.GetDriveInfo

And I can close it with CTRL+C.

GoldtreePy is a direct clone of master, Goldtree is 0.6.1.

**Comment by friedkeenan** [comment]
Your Goldleaf needs to be 0.7

**Comment by gabn88** [comment]
Works like a pro, thanks!
