### ISSUE TITLE
Program is not exiting after installation and keeps reading

### ISSUE THREAD

**Issue by insalada** [friedkeenan/GoldtreePy#18]
I've just did a very rude workaround in my fork (https://github.com/insalada/GoldtreePy) which is just a simple GUI in order to be able to pick up a NSP file via dialog, in which I had to modify that part just exiting the reading loop when it fails instead of passing in case the installation has started...it's ugly I know...but didn't want to touch the original code just for a GUI.

It's not exactly an issue, but I thought you might want to be aware.

Cheers

**Comment by friedkeenan** [comment]
It continuing to listen for commands is expected, correct behavior
