### ISSUE TITLE
Support Goldleaf 0.8

### ISSUE THREAD

**Issue by pheki** [friedkeenan/GoldtreePy#20]
XorTroll has since released Goldleaf 0.8 which makes some changes to the USB protocol, (including the addition of StartFile and EndFile, making it explicit when opening the files to `write_file` and `read_file`) and maybe some other things.

Also thanks for this tool :)

**Comment by friedkeenan** [comment]
Fixed with 741afc30a9d78555a677e6475d8b230f4f90d08d
