### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by LyfeOnEdge** [friedkeenan/GoldtreePy#9]
Could you create an official release at https://github.com/friedkeenan/GoldtreePy/releases?
This would allow users to access it via the github api. You don't need to include a zip with the release, just marking a version as a release will allow the source to be accessed as it was at that point in time. I'd like to add your software as an optional download as well as use my app to provide a graphical frontend with my app: https://github.com/LyfeOnEdge/HBUpdater
I'd like to implement the queing of backups via a gui.
Thanks!

**Comment by friedkeenan** [comment]
Done
